In [ ]:
import pandas as pd
import re
import gspread
from oauth2client.service_account import ServiceAccountCredentials

def convert_google_sheet_url(url):
    pattern = r'https://docs\.google\.com/spreadsheets/d/([a-zA-Z0-9-_]+)(/edit#gid=(\d+)|/edit.*)?'
    replacement = lambda m: f'https://docs.google.com/spreadsheets/d/{m.group(1)}/export?' + (f'gid={m.group(3)}&' if m.group(3) else '') + 'format=csv'
    new_url = re.sub(pattern, replacement, url)
    return new_url

# Define function to read Google Sheets directly into a DataFrame
def read_google_sheet(url):
    # Convert the Google Sheets URL to CSV export URL
    csv_url = convert_google_sheet_url(url)

    # Load the CSV into a DataFrame
    df = pd.read_csv(csv_url)
    return df

# Replace with your Google Sheets URL
google_sheets_url = 'https://docs.google.com/spreadsheets/d'

# Read the Google Sheets document into a DataFrame
df = read_google_sheet(google_sheets_url)

# Convert the 'payment date' column to datetime if it's not already
df['payment date'] = pd.to_datetime(df['payment date'], format='%d/%m/%Y %H:%M:%S')

# Sort the DataFrame by the 'payment date' column in descending order (latest to oldest)
df_sorted = df.sort_values(by='payment date', ascending=False)

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Display the sorted DataFrame
df_sorted

,payment page id,payment page title,payment date,order_id,item name,item amount,item quantity,item payment amount,total payment amount,currency,payment status,payment id,full_name,email,phone,college_name,referral_code,size_of_t_shirt
378,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-14 22:43:53,order_NmJVUsETjk5IaQ,Quizathon,120,1,120,620,INR,captured,pay_NmJVnzfwafQHYZ,Nikhil vikas shinde,shindenikhil2468@gmail.com,9004282620,Indian maritime university kolkata campus,SM24CA05,XL
377,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-14 22:43:53,order_NmJVUsETjk5IaQ,Tshirt,350,1,350,620,INR,captured,pay_NmJVnzfwafQHYZ,Nikhil vikas shinde,shindenikhil2468@gmail.com,9004282620,Indian maritime university kolkata campus,SM24CA05,XL
376,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-14 22:43:53,order_NmJVUsETjk5IaQ,Registration Fees,150,1,150,620,INR,captured,pay_NmJVnzfwafQHYZ,Nikhil vikas shinde,shindenikhil2468@gmail.com,9004282620,Indian maritime university kolkata campus,SM24CA05,XL
368,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-14 22:25:51,order_NmJCeHPHBd0GVJ,Tshirt,350,1,350,620,INR,captured,pay_NmJClZp9vo1y2w,Ravi Prakash Upadhayay,raviprakash9005799767@gmail.com,9005799767,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,SM24CA05,XXL
369,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-14 22:25:51,order_NmJCeHPHBd0GVJ,Quizathon,120,1,120,620,INR,captured,pay_NmJClZp9vo1y2w,Ravi Prakash Upadhayay,raviprakash9005799767@gmail.com,9005799767,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,SM24CA05,XXL
370,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-14 22:25:51,order_NmJCeHPHBd0GVJ,Registration Fees,150,1,150,620,INR,captured,pay_NmJClZp9vo1y2w,Ravi Prakash Upadhayay,raviprakash9005799767@gmail.com,9005799767,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,SM24CA05,XXL
364,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-14 22:18:56,order_NmJ5BOx4C80O4f,Registration Fees,150,1,150,620,INR,captured,pay_NmJ5SJin6vXVtC,Amit Rahul Sardar,amitsardar8082@gmail.com,9860320840,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,SM24CA05,M
363,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-14 22:18:56,order_NmJ5BOx4C80O4f,Tshirt,350,1,350,620,INR,captured,pay_NmJ5SJin6vXVtC,Amit Rahul Sardar,amitsardar8082@gmail.com,9860320840,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,SM24CA05,M
362,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-14 22:18:56,order_NmJ5BOx4C80O4f,Quizathon,120,1,120,620,INR,captured,pay_NmJ5SJin6vXVtC,Amit Rahul Sardar,amitsardar8082@gmail.com,9860320840,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,SM24CA05,M
367,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-14 22:07:52,order_NmIteaJ4hXGFxm,Quizathon,120,1,120,620,INR,captured,pay_NmItlF5WVavI2S,ADARSH LONDHE,adarshlondhe41447@gmail.com,7021766957,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,SM24CA05,M
366,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-14 22:07:52,order_NmIteaJ4hXGFxm,Tshirt,350,1,350,620,INR,captured,pay_NmItlF5WVavI2S,ADARSH LONDHE,adarshlondhe41447@gmail.com,7021766957,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,SM24CA05,M
365,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-14 22:07:52,order_NmIteaJ4hXGFxm,Registration Fees,150,1,150,620,INR,captured,pay_NmItlF5WVavI2S,ADARSH LONDHE,adarshlondhe41447@gmail.com,7021766957,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,SM24CA05,M
358,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-14 21:40:21,order_NmIQa1jsmL9hlu,Tshirt,350,1,350,620,INR,captured,pay_NmIQhHRRXQFMSI,SAURAV BHUSHAN,sr8429927@gmail.com,7488330393,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,SM24CA05,M
357,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-14 21:40:21,order_NmIQa1jsmL9hlu,Registration Fees,150,1,150,620,INR,captured,pay_NmIQhHRRXQFMSI,SAURAV BHUSHAN,sr8429927@gmail.com,7488330393,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,SM24CA05,M
356,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-14 21:40:21,order_NmIQa1jsmL9hlu,Quizathon,120,1,120,620,INR,captured,pay_NmIQhHRRXQFMSI,SAURAV BHUSHAN,sr8429927@gmail.com,7488330393,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,SM24CA05,M
355,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-14 21:35:23,order_NmILFRHzdcwEZC,Tshirt,350,1,350,620,INR,failed,pay_NmILRaFUrnG4QH,SAURAV BHUSHAN,sr8429927@gmail.com,7488330393,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,SM24CA05,M
353,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-14 21:35:23,order_NmILFRHzdcwEZC,Quizathon,120,1,120,620,INR,failed,pay_NmILRaFUrnG4QH,SAURAV BHUSHAN,sr8429927@gmail.com,7488330393,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,SM24CA05,M
354,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-14 21:35:23,order_NmILFRHzdcwEZC,Registration Fees,150,1,150,620,INR,failed,pay_NmILRaFUrnG4QH,SAURAV BHUSHAN,sr8429927@gmail.com,7488330393,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,SM24CA05,M
359,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-14 21:29:02,order_NmIDo3vR04Dp6Z,Registration Fees,150,1,150,620,INR,captured,pay_NmIEkVnJrWxNaV,SANSKAR SAGAR,sagarsanskar5@gmail.com,7544019877,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,SM24CA05,M
361,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-14 21:29:02,order_NmIDo3vR04Dp6Z,Tshirt,350,1,350,620,INR,captured,pay_NmIEkVnJrWxNaV,SANSKAR SAGAR,sagarsanskar5@gmail.com,7544019877,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,SM24CA05,M
360,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-14 21:29:02,order_NmIDo3vR04Dp6Z,Quizathon,120,1,120,620,INR,captured,pay_NmIEkVnJrWxNaV,SANSKAR SAGAR,sagarsanskar5@gmail.com,7544019877,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,SM24CA05,M
338,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 23:56:52,order_NlwDaA1vR6J13p,Boat Wars,150,1,150,650,INR,captured,pay_NlwDmpZvSC1kXm,Raghav Neekhra,raghavn801@gmail.com,8349780719,"Indian Maritime University, Kolkata Campus",SM24CA05,M
337,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 23:56:52,order_NlwDaA1vR6J13p,Tshirt,350,1,350,650,INR,captured,pay_NlwDmpZvSC1kXm,Raghav Neekhra,raghavn801@gmail.com,8349780719,"Indian Maritime University, Kolkata Campus",SM24CA05,M
336,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 23:56:52,order_NlwDaA1vR6J13p,Registration Fees,150,1,150,650,INR,captured,pay_NlwDmpZvSC1kXm,Raghav Neekhra,raghavn801@gmail.com,8349780719,"Indian Maritime University, Kolkata Campus",SM24CA05,M
332,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 23:50:19,order_Nlw6jl8oSlgshc,Tshirt,350,1,350,1250,INR,captured,pay_Nlw6rneUpBOKaV,Rajeenta Bara,rajeentabara12@gmail.com,7061130842,Indian Maritime University,SM24CA05,L
329,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 23:50:19,order_Nlw6jl8oSlgshc,Boat Wars,150,1,150,1250,INR,captured,pay_Nlw6rneUpBOKaV,Rajeenta Bara,rajeentabara12@gmail.com,7061130842,Indian Maritime University,SM24CA05,L
330,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 23:50:19,order_Nlw6jl8oSlgshc,Accommodation,600,1,600,1250,INR,captured,pay_Nlw6rneUpBOKaV,Rajeenta Bara,rajeentabara12@gmail.com,7061130842,Indian Maritime University,SM24CA05,L
331,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 23:50:19,order_Nlw6jl8oSlgshc,Registration Fees,150,1,150,1250,INR,captured,pay_Nlw6rneUpBOKaV,Rajeenta Bara,rajeentabara12@gmail.com,7061130842,Indian Maritime University,SM24CA05,L
438,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 23:49:34,order_Nlw5VchbEcOLgF,Boat Wars,150,1,150,1250,INR,captured,pay_Nlw64LHTKnP6tZ,Ronit Bal,balronit@gmail.com,917004400647,"Indian Maritime University, Kolkata Campus",SM24CA05,M
439,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 23:49:34,order_Nlw5VchbEcOLgF,Accommodation,600,1,600,1250,INR,captured,pay_Nlw64LHTKnP6tZ,Ronit Bal,balronit@gmail.com,917004400647,"Indian Maritime University, Kolkata Campus",SM24CA05,M
440,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 23:49:34,order_Nlw5VchbEcOLgF,Registration Fees,150,1,150,1250,INR,captured,pay_Nlw64LHTKnP6tZ,Ronit Bal,balronit@gmail.com,917004400647,"Indian Maritime University, Kolkata Campus",SM24CA05,M
441,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 23:49:34,order_Nlw5VchbEcOLgF,Tshirt,350,1,350,1250,INR,captured,pay_Nlw64LHTKnP6tZ,Ronit Bal,balronit@gmail.com,917004400647,"Indian Maritime University, Kolkata Campus",SM24CA05,M
435,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 23:49:29,order_Nlw5psOSUE9p25,Boat Wars,150,1,150,1250,INR,captured,pay_Nlw5yi7vWJahsY,Rakesh Suman,rakeshgyan2004@gmail.com,8539851466,Indian Maritime University Kolkata campus,SM24CA06,M
434,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 23:49:29,order_Nlw5psOSUE9p25,Accommodation,600,1,600,1250,INR,captured,pay_Nlw5yi7vWJahsY,Rakesh Suman,rakeshgyan2004@gmail.com,8539851466,Indian Maritime University Kolkata campus,SM24CA06,M
436,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 23:49:29,order_Nlw5psOSUE9p25,Registration Fees,150,1,150,1250,INR,captured,pay_Nlw5yi7vWJahsY,Rakesh Suman,rakeshgyan2004@gmail.com,8539851466,Indian Maritime University Kolkata campus,SM24CA06,M
437,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 23:49:29,order_Nlw5psOSUE9p25,Tshirt,350,1,350,1250,INR,captured,pay_Nlw5yi7vWJahsY,Rakesh Suman,rakeshgyan2004@gmail.com,8539851466,Indian Maritime University Kolkata campus,SM24CA06,M
391,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 13:47:21,order_NllnV7XGXPcw7X,Boat Wars,150,1,150,650,INR,captured,pay_NllpvfoKFavZKA,gokul siva m,gokul95195@gmail.com,9442395195,imu kolkata,NaN,XL
392,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 13:47:21,order_NllnV7XGXPcw7X,Registration Fees,150,1,150,650,INR,captured,pay_NllpvfoKFavZKA,gokul siva m,gokul95195@gmail.com,9442395195,imu kolkata,NaN,XL
393,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 13:47:21,order_NllnV7XGXPcw7X,Tshirt,350,1,350,650,INR,captured,pay_NllpvfoKFavZKA,gokul siva m,gokul95195@gmail.com,9442395195,imu kolkata,NaN,XL
418,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 12:48:44,order_Nlkox4z3p81Qwg,Tshirt,350,1,350,1475,INR,captured,pay_Nlkq0upSKFc4OU,Ashutosh shrivastav,shrivastavvickyiit@gmail.com,8707063520,Indian maritime university Visakhapatnam campus,SM24CA10,L
416,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 12:48:44,order_Nlkox4z3p81Qwg,Accommodation,600,1,600,1475,INR,captured,pay_Nlkq0upSKFc4OU,Ashutosh shrivastav,shrivastavvickyiit@gmail.com,8707063520,Indian maritime university Visakhapatnam campus,SM24CA10,L
415,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 12:48:44,order_Nlkox4z3p81Qwg,Boat Wars,150,1,150,1475,INR,captured,pay_Nlkq0upSKFc4OU,Ashutosh shrivastav,shrivastavvickyiit@gmail.com,8707063520,Indian maritime university Visakhapatnam campus,SM24CA10,L
414,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 12:48:44,order_Nlkox4z3p81Qwg,Ocean Oddessey,150,1,150,1475,INR,captured,pay_Nlkq0upSKFc4OU,Ashutosh shrivastav,shrivastavvickyiit@gmail.com,8707063520,Indian maritime university Visakhapatnam campus,SM24CA10,L
413,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 12:48:44,order_Nlkox4z3p81Qwg,Cryptic Clues,75,1,75,1475,INR,captured,pay_Nlkq0upSKFc4OU,Ashutosh shrivastav,shrivastavvickyiit@gmail.com,8707063520,Indian maritime university Visakhapatnam campus,SM24CA10,L
417,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-13 12:48:44,order_Nlkox4z3p81Qwg,Registration Fees,150,1,150,1475,INR,captured,pay_Nlkq0upSKFc4OU,Ashutosh shrivastav,shrivastavvickyiit@gmail.com,8707063520,Indian maritime university Visakhapatnam campus,SM24CA10,L
328,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:11:25,order_NlWuQKoE1Vy1q6,Registration Fees,150,1,150,1620,INR,captured,pay_NlWue01JC7zoQT,Jayesh Gajanan Ganode,jayeshganode@gmail.com,9970181106,Indian Maritime University Kolkata Campus,SM24CA05,L
324,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:11:25,order_NlWuQKoE1Vy1q6,Wave Quest,120,1,120,1620,INR,captured,pay_NlWue01JC7zoQT,Jayesh Gajanan Ganode,jayeshganode@gmail.com,9970181106,Indian Maritime University Kolkata Campus,SM24CA05,L
325,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:11:25,order_NlWuQKoE1Vy1q6,Boat Wars,150,1,150,1620,INR,captured,pay_NlWue01JC7zoQT,Jayesh Gajanan Ganode,jayeshganode@gmail.com,9970181106,Indian Maritime University Kolkata Campus,SM24CA05,L
326,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:11:25,order_NlWuQKoE1Vy1q6,Accommodation,600,1,600,1620,INR,captured,pay_NlWue01JC7zoQT,Jayesh Gajanan Ganode,jayeshganode@gmail.com,9970181106,Indian Maritime University Kolkata Campus,SM24CA05,L
327,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:11:25,order_NlWuQKoE1Vy1q6,Tshirt,350,1,350,1620,INR,captured,pay_NlWue01JC7zoQT,Jayesh Gajanan Ganode,jayeshganode@gmail.com,9970181106,Indian Maritime University Kolkata Campus,SM24CA05,L
322,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:11:25,order_NlWuQKoE1Vy1q6,Ocean Oddessey,150,1,150,1620,INR,captured,pay_NlWue01JC7zoQT,Jayesh Gajanan Ganode,jayeshganode@gmail.com,9970181106,Indian Maritime University Kolkata Campus,SM24CA05,L
323,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:11:25,order_NlWuQKoE1Vy1q6,Deep Sea Disputes,100,1,100,1620,INR,captured,pay_NlWue01JC7zoQT,Jayesh Gajanan Ganode,jayeshganode@gmail.com,9970181106,Indian Maritime University Kolkata Campus,SM24CA05,L
297,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:05:26,order_NlWnjpBW6fVW9o,Quizathon,120,1,120,1370,INR,captured,pay_NlWoKSuXGPsMxJ,Mohammad waris Quraishi,mohammadwarisquraishi93@gmail.com,9305733464,Indian maritime University Kolkata campus,SM24CA05,L
298,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:05:26,order_NlWnjpBW6fVW9o,Boat Wars,150,1,150,1370,INR,captured,pay_NlWoKSuXGPsMxJ,Mohammad waris Quraishi,mohammadwarisquraishi93@gmail.com,9305733464,Indian maritime University Kolkata campus,SM24CA05,L
300,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:05:26,order_NlWnjpBW6fVW9o,Tshirt,350,1,350,1370,INR,captured,pay_NlWoKSuXGPsMxJ,Mohammad waris Quraishi,mohammadwarisquraishi93@gmail.com,9305733464,Indian maritime University Kolkata campus,SM24CA05,L
301,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:05:26,order_NlWnjpBW6fVW9o,Accommodation,600,1,600,1370,INR,captured,pay_NlWoKSuXGPsMxJ,Mohammad waris Quraishi,mohammadwarisquraishi93@gmail.com,9305733464,Indian maritime University Kolkata campus,SM24CA05,L
299,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:05:26,order_NlWnjpBW6fVW9o,Registration Fees,150,1,150,1370,INR,captured,pay_NlWoKSuXGPsMxJ,Mohammad waris Quraishi,mohammadwarisquraishi93@gmail.com,9305733464,Indian maritime University Kolkata campus,SM24CA05,L
318,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:04:34,order_NlWmkgV2bOKL0K,Ocean Oddessey,150,1,150,1620,INR,failed,pay_NlWnQKb1JcT2lk,Jayesh Gajanan Ganode,jayeshganode@gmail.com,9970181106,Indian Maritime University Kolkata Campus,SM24CA05,L
320,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:04:34,order_NlWmkgV2bOKL0K,Accommodation,600,1,600,1620,INR,failed,pay_NlWnQKb1JcT2lk,Jayesh Gajanan Ganode,jayeshganode@gmail.com,9970181106,Indian Maritime University Kolkata Campus,SM24CA05,L
315,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:04:34,order_NlWmkgV2bOKL0K,Deep Sea Disputes,100,1,100,1620,INR,failed,pay_NlWnQKb1JcT2lk,Jayesh Gajanan Ganode,jayeshganode@gmail.com,9970181106,Indian Maritime University Kolkata Campus,SM24CA05,L
316,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:04:34,order_NlWmkgV2bOKL0K,Wave Quest,120,1,120,1620,INR,failed,pay_NlWnQKb1JcT2lk,Jayesh Gajanan Ganode,jayeshganode@gmail.com,9970181106,Indian Maritime University Kolkata Campus,SM24CA05,L
317,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:04:34,order_NlWmkgV2bOKL0K,Tshirt,350,1,350,1620,INR,failed,pay_NlWnQKb1JcT2lk,Jayesh Gajanan Ganode,jayeshganode@gmail.com,9970181106,Indian Maritime University Kolkata Campus,SM24CA05,L
319,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:04:34,order_NlWmkgV2bOKL0K,Boat Wars,150,1,150,1620,INR,failed,pay_NlWnQKb1JcT2lk,Jayesh Gajanan Ganode,jayeshganode@gmail.com,9970181106,Indian Maritime University Kolkata Campus,SM24CA05,L
321,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:04:34,order_NlWmkgV2bOKL0K,Registration Fees,150,1,150,1620,INR,failed,pay_NlWnQKb1JcT2lk,Jayesh Gajanan Ganode,jayeshganode@gmail.com,9970181106,Indian Maritime University Kolkata Campus,SM24CA05,L
302,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:00:58,order_NlWiqS9eI6jox4,Accommodation,600,1,600,1620,INR,captured,pay_NlWjbwLxYdEYQm,Ishan Singh,ishansingh2708s@gmail.com,8218542013,Indian Maritime University Kolkata,SM24CA05,M
303,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:00:58,order_NlWiqS9eI6jox4,Ocean Oddessey,150,1,150,1620,INR,captured,pay_NlWjbwLxYdEYQm,Ishan Singh,ishansingh2708s@gmail.com,8218542013,Indian Maritime University Kolkata,SM24CA05,M
304,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:00:58,order_NlWiqS9eI6jox4,Wave Quest,120,1,120,1620,INR,captured,pay_NlWjbwLxYdEYQm,Ishan Singh,ishansingh2708s@gmail.com,8218542013,Indian Maritime University Kolkata,SM24CA05,M
305,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:00:58,order_NlWiqS9eI6jox4,Registration Fees,150,1,150,1620,INR,captured,pay_NlWjbwLxYdEYQm,Ishan Singh,ishansingh2708s@gmail.com,8218542013,Indian Maritime University Kolkata,SM24CA05,M
306,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:00:58,order_NlWiqS9eI6jox4,Deep Sea Disputes,100,1,100,1620,INR,captured,pay_NlWjbwLxYdEYQm,Ishan Singh,ishansingh2708s@gmail.com,8218542013,Indian Maritime University Kolkata,SM24CA05,M
307,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:00:58,order_NlWiqS9eI6jox4,Boat Wars,150,1,150,1620,INR,captured,pay_NlWjbwLxYdEYQm,Ishan Singh,ishansingh2708s@gmail.com,8218542013,Indian Maritime University Kolkata,SM24CA05,M
308,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 23:00:58,order_NlWiqS9eI6jox4,Tshirt,350,1,350,1620,INR,captured,pay_NlWjbwLxYdEYQm,Ishan Singh,ishansingh2708s@gmail.com,8218542013,Indian Maritime University Kolkata,SM24CA05,M
289,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 22:55:40,order_NlWd7RVey5rMYl,Deep Sea Disputes,100,1,100,1620,INR,captured,pay_NlWe0X4ESOlegV,Durai murugan T,durai30122002@gmail.com,8438956689,Indian maritime university kolkata campus,SM24CA05,L
288,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 22:55:40,order_NlWd7RVey5rMYl,Accommodation,600,1,600,1620,INR,captured,pay_NlWe0X4ESOlegV,Durai murugan T,durai30122002@gmail.com,8438956689,Indian maritime university kolkata campus,SM24CA05,L
284,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 22:55:40,order_NlWd7RVey5rMYl,Wave Quest,120,1,120,1620,INR,captured,pay_NlWe0X4ESOlegV,Durai murugan T,durai30122002@gmail.com,8438956689,Indian maritime university kolkata campus,SM24CA05,L
285,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 22:55:40,order_NlWd7RVey5rMYl,Ocean Oddessey,150,1,150,1620,INR,captured,pay_NlWe0X4ESOlegV,Durai murugan T,durai30122002@gmail.com,8438956689,Indian maritime university kolkata campus,SM24CA05,L
287,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 22:55:40,order_NlWd7RVey5rMYl,Registration Fees,150,1,150,1620,INR,captured,pay_NlWe0X4ESOlegV,Durai murugan T,durai30122002@gmail.com,8438956689,Indian maritime university kolkata campus,SM24CA05,L
286,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 22:55:40,order_NlWd7RVey5rMYl,Boat Wars,150,1,150,1620,INR,captured,pay_NlWe0X4ESOlegV,Durai murugan T,durai30122002@gmail.com,8438956689,Indian maritime university kolkata campus,SM24CA05,L
290,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 22:55:40,order_NlWd7RVey5rMYl,Tshirt,350,1,350,1620,INR,captured,pay_NlWe0X4ESOlegV,Durai murugan T,durai30122002@gmail.com,8438956689,Indian maritime university kolkata campus,SM24CA05,L
309,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 10:03:48,order_NlJURllNopc8FC,Boat Wars,150,1,150,1520,INR,captured,pay_NlJUfeOZrnSz5R,Rachit Monga,rachitmonga12@gmail.com,8439880128,"IMU, VIZAG",SM24CA10,L
314,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 10:03:48,order_NlJURllNopc8FC,Tshirt,350,1,350,1520,INR,captured,pay_NlJUfeOZrnSz5R,Rachit Monga,rachitmonga12@gmail.com,8439880128,"IMU, VIZAG",SM24CA10,L
313,pl_NNgBrunNYA8Iqc,Registration Page,2024-03-12 10:03:48,order_NlJURllNopc8FC,Registration Fees,150,1,150,1520,INR,captured,pay_NlJUfeOZrnSz5R,Rachit Monga,rachitmonga12@gmail.com,8439880128,"IMU, VIZAG",SM24CA10,L

In [ ]:
# Grouping by 'full_name' and aggregating other columns
grouped_data = df_sorted.groupby('full_name').agg({
    'payment date': 'max',  # Assuming you want the latest payment date for each person
    'email': 'first',
    'phone': 'first',
    'college_name': 'first',
    'size_of_t_shirt': 'first',
    'item name': lambda x: list(x)
})

# Sort the DataFrame by the 'payment date' column in descending order (latest to oldest)
grouped_data = grouped_data.sort_values(by='payment date', ascending=True)

# Print the result
grouped_data

,payment date,email,phone,college_name,size_of_t_shirt,item name
full_name,,,,,,
Abijith Krishna Murali,2024-01-19 08:31:13,abijithkrishnamurali@gmail.com,9778588680,"INDIAN MARITIME UNIVERSITY, VISAKHAPATNAM CAMPUS",M,"[Registration Fees, Ocean Oddessey, Accommodat..."
SAGNIK SARKAR,2024-01-19 17:00:53,sagniksarkar2410@gmail.com,9123794787,"INDIAN MARITIME UNIVERSITY, VISAKHAPATNAM",L,"[Tshirt, Registration Fees, Accommodation, Cry..."
Akshit kumar,2024-01-21 12:03:05,akshitbibha@gmail.com,9470160657,Imu kolkata,M,"[Boat Wars, Tshirt, Cryptic Clues, Registratio..."
Gavara Naveen,2024-01-25 12:06:34,naveen.gavara2004@gmail.com,8639871084,"Indian Maritime University, Visakhapatnam",M,"[Tshirt, Registration Fees, Ocean Oddessey]"
Gaautham Gireesh,2024-02-13 22:01:31,gautham20032003@gmail.com,7034814709,"Indian Maritime University, Visakhapatnam",XXL,"[Registration Fees, Accommodation, Ocean Oddes..."
Ayana Anil,2024-02-14 14:38:46,ayanaalakapuri@gmail.com,9400359629,"Indian Maritime University, Visakhapatnam",L,"[Accommodation, Registration Fees, Wave Quest,..."
Rizwan Ahmed F.,2024-02-14 22:12:49,rizwanloyolite2004@gmail.com,9400327772,Indian Maritime University Visakhapatnam,L,"[Accommodation, Ocean Oddessey, Wave Quest, Ts..."
Liana Elizabeth Kurien,2024-02-15 10:48:50,Lianaelizabeth04@gmail.com,9605872064,"Indian Maritime University, Visakhapatnam",XL,"[Accommodation, Registration Fees, Tshirt, Wav..."
Tanuja,2024-02-20 22:05:21,tanubansal1302@gmail.com,8901619544,"Indian Maritime University, Visakhapatnam campus",M,"[Boat Wars, Accommodation, Tshirt, Ocean Oddes..."
Rudrajit Banerjee,2024-02-21 00:42:55,rudrajitbanerjee269@gmail.com,8918155606,"Indian Maritime University, Visakhapatnam Campus",L,"[Wave Quest, Boat Wars, Accommodation, Cryptic..."
Ikia Maria de Jesus Coelho,2024-02-21 18:39:33,ikiamergulhao01@gmail.com,7083861406,"Indian Maritime University, Visakhapatnam Campus",L,"[Tshirt, Wave Quest, Ocean Oddessey, Cryptic C..."
Richa Ahirwar,2024-02-22 14:46:28,ahirwarricha9044@gmail.com,6386228957,Indian maritime university,XL,"[Registration Fees, Wave Quest, Cryptic Clues,..."
Ishika Dutta,2024-02-22 14:48:08,ishikadutta2003@gmail.com,6296193241,"INDIAN MARITIME UNIVERSITY, VISAKHAPATNAM CAMPUS",XL,"[Cryptic Clues, Deep Sea Disputes, Registratio..."
Subhrajyoti Sarkar,2024-02-25 11:35:37,subhrajyotisarakar@gmail.com,7003310566,Indian Maritime University Vizag,XL,"[Tshirt, Cryptic Clues, Registration Fees, Acc..."
Shayal Tyni,2024-02-26 00:17:42,shayaltyni@gmail.com,9656491969,"Indian maritime university, Visakhapatnam",S,"[Wave Quest, Accommodation, Tshirt, Registrati..."
AKANKSHAYA PRIYADARSHINI RATHA,2024-02-29 00:01:03,apr.thuku22@gmail.com,9439140337,"Indian Maritime University, Visakhapatnam Campus",M,"[Ocean Oddessey, Tshirt, Deep Sea Disputes, Re..."
Erin Anto,2024-02-29 00:09:16,erinan3102@gmail.com,9778228578,"Indian Maritime University, Vishakhapatnam",S,"[Ocean Oddessey, Registration Fees, Tshirt, Ac..."
Ritika Haridas Nair,2024-03-01 12:31:10,ritikahari@gmail.com,9372382303,Indian Maritime University Visakhapatnam Campus,L,"[Registration Fees, Ocean Oddessey, Accommodat..."
Dharmi Changela,2024-03-01 19:23:47,dharmi82002@gmail.com,6377463767,Indian Maritime University Visakhapatnam Campus,L,"[Quizathon, Ocean Oddessey, Cryptic Clues, Acc..."
K SHRUTHI,2024-03-01 19:28:45,kshruthi130202@gmail.com,9679561237,"INDIAN MARITIME UNIVERSITY, VISAKHAPATNAM CAMPUS",L,"[Tshirt, Cryptic Clues, Accommodation, Registr..."
Md Sadique Siddiquee,2024-03-04 21:49:00,mdsadiquesiddiquee786@gmail.com,9608982535,Indian Maritime University - Kolkata Campus,M,"[Boat Wars, Tshirt, Registration Fees]"
Sabit Najeeb,2024-03-04 21:59:11,sabitnajeeb10@gmail.com,9827548083,Indian maritime University Kolkata campus,M,"[Tshirt, Registration Fees]"
Farhan Rana,2024-03-04 22:04:56,fr782096@gmail.com,7273049804,Indian Maritime University - Kolkata Campus,M,"[Registration Fees, Tshirt]"
Kashif Irshad,2024-03-04 22:05:00,imkashif1414@gmail.com,7488673306,Indian maritime University Kolkata campus,M,"[Tshirt, Registration Fees]"
Ayush Deep,2024-03-06 17:52:55,ayushdeep221@gmail.com,9523272277,"Indian Maritime University, Visakhapatnam",M,"[Ocean Oddessey, Aqua Exposure, Wave Quest, Bo..."
Ayan Angshu Acharjya,2024-03-07 17:43:16,ayanacharjya373@gmail.com,8822466047,"Training Ship Chanakya, Indian Maritime Univer...",S,"[Accommodation, Deep Sea Disputes, Quizathon, ..."
Nishant Dadwal,2024-03-07 20:45:39,nishant7021acm@gmail.com,7837647021,INDIAN MARITIME UNIVERSITY NAVI MUMBAI,L,"[Registration Fees, Quizathon, Ocean Oddessey,..."
Harshit,2024-03-07 21:43:36,bainslaharshit969@gmail.com,7404402310,T.S. Chanakya (IMU NMC),M,"[Ocean Oddessey, Cryptic Clues, Accommodation,..."
Abhishek Bhardwaj,2024-03-07 21:44:25,abhibhardwaj473@gmail.com,8219422095,IMU NAVI MUMBAI CAMPUS (T.S chanakya),L,"[Tshirt, Registration Fees, Accommodation, Aqu..."
Anupriya,2024-03-07 21:46:13,8529anupriya29@gmail.com,9870211462,"T. S chanakya, IMU navi mumbai",M,"[Tshirt, Cryptic Clues, Ocean Oddessey, Accomm..."
OM PRAKASH GAUTAM,2024-03-07 21:48:15,om456pga@gmail.com,9334073218,IMU-Navi Mumbai Campus (T. S. Chanakya),L,"[Cryptic Clues, Quizathon, Accommodation, Tshi..."
Soubhagya Ranjan Mantry,2024-03-07 23:04:17,soubhagyaranjanmantry018@gmail.com,7438917150,"Indian Maritime University, Visakhapatnam",L,"[Wave Quest, Cryptic Clues, Registration Fees,..."
Sai Pranay,2024-03-08 16:13:21,8621saipranay@gmail.com,8928990727,"IMU Navi Mumbai ,TS Chanakya",M,"[Registration Fees, Deep Sea Disputes, Quizath..."
RAJDEEP DAS,2024-03-08 19:37:39,drajdeep399@gmail.com,916296672307,INDIAN MARITIME UNIVERSITY,XL,"[Quizathon, Deep Sea Disputes, Ocean Oddessey,..."
Saideep Nagvekar,2024-03-08 23:25:59,saideepss19619@gmail.com,8806884209,Indian Maritime University Kolkata campus,XL,"[Tshirt, Registration Fees, Boat Wars]"
Renard Quadros,2024-03-08 23:29:19,renardquadros@gmail.com,9370390221,Indian maritime University Kolkata campus,L,"[Boat Wars, Tshirt, Registration Fees]"
Rohan Dhole,2024-03-08 23:32:33,rohandhole0214@gmail.com,8459424628,Indian Maritime University Kolkata campus,M,"[Tshirt, Registration Fees, Boat Wars]"
Vishal Das,2024-03-08 23:33:16,dasvishal64@gmail.com,8017050376,"Indian Maritime University, Kolkata Campus",L,"[Wave Quest, Deep Sea Disputes, Tshirt, Regist..."
Astik Raikar,2024-03-08 23:43:50,astikraikar11@gmail.com,9021084937,Indian Maritime University Kolkata Campus,L,"[Tshirt, Boat Wars, Registration Fees, Boat Wa..."
Kanishk Sunhare,2024-03-09 00:10:31,kanishk18sunhare@gmail.com,9302120457,"Indian Maritime University, Kolkata Campus",XL,"[Accommodation, Boat Wars, Deep Sea Disputes, ..."
Abhimanyu Singh,2024-03-09 08:05:23,abhimanyunavydbd@gmail.com,8791393412,Indian Maritime University Kolkata Campus,M,"[Deep Sea Disputes, Tshirt, Registration Fees,..."
Aryan Chouhan,2024-03-09 09:56:03,aaryac811@gamil.com,8777641879,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,M,"[Registration Fees, Tshirt, Cryptic Clues]"
Cadet Sushan Mukherjee,2024-03-09 11:29:35,sushanmukherjee157@gmail.com,8750188929,Indian Maritime University Kolkata Campus,M,"[Ocean Oddessey, Aqua Exposure, Accommodation,..."
Bhadra Vazhappully,2024-03-09 12:59:29,bhadraaanoop@gmail.com,9447467227,"Indian Maritime University, Visakhapatnam",M,"[Accommodation, Wave Quest, Registration Fees,..."
G S Ganga Nandan,2024-03-09 13:00:01,gangaganguzz15@gmail.com,8891604253,"Indian Maritime University, Visakhapatnam Campus",L,"[Tshirt, Accommodation, Registration Fees, Wav..."
Amritha Krishnan N J,2024-03-09 13:01:04,amrithajayaraj@gmail.com,6282926128,"Indian Maritime University, Visakhapatnam Campus",L,"[Wave Quest, Tshirt, Ocean Oddessey, Registrat..."
Rutuj Kamble,2024-03-09 20:55:00,rutujkamble753@gmail.com,9082030959,Indian Maritime University Kolkata Campus ampus,L,"[Tshirt, Registration Fees, Cryptic Clues]"
Devansh khare,2024-03-09 21:07:51,kharedevansh18@gmail.com,9389547826,Indian Maritime University Kolkata Campus,XL,"[Registration Fees, Tshirt, Quizathon]"
Jainendra Kumar Bhaskar,2024-03-09 21:07:53,jainendra9534@gmail.com,7004275481,Indian maritime University Kolkata campus,L,"[Tshirt, Quizathon, Registration Fees]"
Vipul Bhashkar,2024-03-09 21:08:23,vipulbhashkar1303@gmail.com,9304472389,Indian Maritime University Kolkata Campus,L,"[Quizathon, Tshirt, Registration Fees]"
Gautam Raj Sinha,2024-03-09 21:09:25,gautamrajsinha0512@gmail.com,7079516634,"Indian Maritime University, Kolkata Campus",XL,"[Tshirt, Quizathon, Registration Fees]"
Cadet Suryashish Guha,2024-03-09 21:14:51,suryashish2005@gmail.com,8910572885,Indian Maritime University Kolkata Campus,L,"[Tshirt, Quizathon, Registration Fees]"
Mohit Sharma,2024-03-09 22:14:49,mohits9h9a1@gmail.com,7903640139,Indian Maritime University Kolkata campus,M,"[Cryptic Clues, Tshirt, Registration Fees]"
Mohit Kumar Arya,2024-03-09 22:16:59,mohitkumararya9953@gmail.com,7003870240,Indian Maritime University Kolkata,M,"[Cryptic Clues, Tshirt, Registration Fees]"
Aditya Kukreti,2024-03-09 22:23:14,adityakukreti2006@gmail.com,7668217140,Indian Maritime University Kolkata,M,"[Registration Fees, Tshirt, Deep Sea Disputes,..."
Aditya Kumar,2024-03-09 23:52:49,aadi723675@gmail.com,8808632003,Indian maritime University Kolkata,M,"[Registration Fees, Tshirt, Cryptic Clues]"
Kartim,2024-03-10 00:04:41,kartiks1256@gmail.com,9667751772,Indian maritime University kolkata,L,"[Tshirt, Cryptic Clues, Registration Fees]"
Mantu kumar,2024-03-10 08:45:30,kumarmantu2705@gmail.com,9430389905,Indian maritime University Kolkata campus,L,"[Tshirt, Quizathon, Registration Fees]"
Sagar kumar,2024-03-10 21:39:43,sagarkumarrajakk1200@gmail.com,8582008462,Indian maritime University Kolkata campus,XL,"[Registration Fees, Quizathon, Tshirt]"
Sagar kumar rajak,2024-03-10 21:41:55,sagarkumarrajakk1200@gmail.com,8582008462,Indian maritime University Kolkata campus,L,"[Registration Fees, Tshirt, Quizathon]"
Aditya Ghosh,2024-03-10 21:51:06,ghoshaditya57@gmail.com,6290217337,"Indian Maritime University, Visakhapatnam",XL,"[Tshirt, Registration Fees, Accommodation, Oce..."
Lavanya V,2024-03-10 22:39:36,lavanyavel.civil@gmail.com,7358186945,Indian Maritime University Vishakapatnam,L,"[Registration Fees, Accommodation, Ocean Oddes..."
Anindya Mukherjee,2024-03-11 09:53:24,mukherjeeanindya6918@gmail.com,9830560329,"Indian Maritime University, Vizag",M,"[Wave Quest, Boat Wars, Aqua Exposure, Registr..."
P.ADITHYA.M.NAIK,2024-03-11 12:25:05,adithyanaik010@gmail.com,8921025539,INDIAN MARITIME UNIVERSITY VISAKHAPATNAM,XL,"[Accommodation, Registration Fees, Cryptic Clu..."
Kunal Sharma,2024-03-11 23:25:46,kunal150404@gmail.com,9311744796,"Indian Maritime University, Kolkata campus",L,"[Tshirt, Accommodation, Aqua Innovate, Registr..."
Harsh Jaiswal,2024-03-11 23:26:18,hj7222685@gmail.com,9039143842,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,L,"[Registration Fees, Aqua Innovate, Tshirt, Acc..."
Rachit Monga,2024-03-12 10:03:48,rachitmonga12@gmail.com,8439880128,"IMU, VIZAG",L,"[Tshirt, Quizathon, Ocean Oddessey, Accommodat..."
Durai murugan T,2024-03-12 22:55:40,durai30122002@gmail.com,8438956689,Indian maritime university kolkata campus,L,"[Ocean Oddessey, Tshirt, Wave Quest, Registrat..."
Ishan Singh,2024-03-12 23:00:58,ishansingh2708s@gmail.com,8218542013,Indian Maritime University Kolkata,M,"[Boat Wars, Wave Quest, Tshirt, Accommodation,..."
Mohammad waris Quraishi,2024-03-12 23:05:26,mohammadwarisquraishi93@gmail.com,9305733464,Indian maritime University Kolkata campus,L,"[Accommodation, Tshirt, Registration Fees, Boa..."
Jayesh Gajanan Ganode,2024-03-12 23:11:25,jayeshganode@gmail.com,9970181106,Indian Maritime University Kolkata Campus,L,"[Wave Quest, Ocean Oddessey, Deep Sea Disputes..."
Ashutosh shrivastav,2024-03-13 12:48:44,shrivastavvickyiit@gmail.com,8707063520,Indian maritime university Visakhapatnam campus,L,"[Ocean Oddessey, Boat Wars, Accommodation, Reg..."
gokul siva m,2024-03-13 13:47:21,gokul95195@gmail.com,9442395195,imu kolkata,XL,"[Boat Wars, Registration Fees, Tshirt]"
Rakesh Suman,2024-03-13 23:49:29,rakeshgyan2004@gmail.com,8539851466,Indian Maritime University Kolkata campus,M,"[Tshirt, Registration Fees, Boat Wars, Accommo..."
Ronit Bal,2024-03-13 23:49:34,balronit@gmail.com,917004400647,"Indian Maritime University, Kolkata Campus",M,"[Boat Wars, Accommodation, Registration Fees, ..."
Rajeenta Bara,2024-03-13 23:50:19,rajeentabara12@gmail.com,7061130842,Indian Maritime University,L,"[Accommodation, Tshirt, Registration Fees, Boa..."
Raghav Neekhra,2024-03-13 23:56:52,raghavn801@gmail.com,8349780719,"Indian Maritime University, Kolkata Campus",M,"[Boat Wars, Tshirt, Registration Fees]"
SANSKAR SAGAR,2024-03-14 21:29:02,sagarsanskar5@gmail.com,7544019877,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,M,"[Tshirt, Quizathon, Registration Fees]"
SAURAV BHUSHAN,2024-03-14 21:40:21,sr8429927@gmail.com,7488330393,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,M,"[Quizathon, Registration Fees, Tshirt, Quizath..."
ADARSH LONDHE,2024-03-14 22:07:52,adarshlondhe41447@gmail.com,7021766957,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,M,"[Quizathon, Registration Fees, Tshirt]"
Amit Rahul Sardar,2024-03-14 22:18:56,amitsardar8082@gmail.com,9860320840,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,M,"[Quizathon, Tshirt, Registration Fees]"
Ravi Prakash Upadhayay,2024-03-14 22:25:51,raviprakash9005799767@gmail.com,9005799767,INDIAN MARITIME UNIVERSITY KOLKATA CAMPUS,XXL,"[Registration Fees, Quizathon, Tshirt]"
Nikhil vikas shinde,2024-03-14 22:43:53,shindenikhil2468@gmail.com,9004282620,Indian maritime university kolkata campus,XL,"[Registration Fees, Quizathon, Tshirt]"

In [ ]:
# Save the grouped data to a new CSV file
grouped_data.to_csv('grouped_data.csv')